### ISSUE TITLE
Introduce a more fine-grained `Resources` effect so `runResource` can be called without requiring `IOE` everywhere

### ISSUE THREAD

**Issue by Qqwy** [haskell-effectful/resourcet-effectful#11]
At work we're using `Conduit` together with `Effectful`. These conduits live deep inside the logic of the app, but because `runResource` is constrained with `IOE :> es`, we had to pass `IOE` all the way deep down into the code.

A solution (which I implemented in our private work codebase, but I'm proposing to upstream to this library) is to introduce a new `Resources` effect. That way you do not need to pass the `IOE` constraint all the way down:

```haskell
module Effectful.Resources where
-- imports elided for brevity

data Resources :: Effect
type instance DispatchOf Resources = Static WithSideEffects
data instance StaticRep Resources = Resources

-- | Discharge the `Resources` effect. Intended to be used high up the effect call stack.
runResources :: (IOE :> es) => Eff (Resources : es) a -> Eff es a
runResources = evalStaticRep Resources

-- | A `Resource` can be discharged iff `Resources` is in scope.
--
-- The implementation of this function closely matches `Effectful.Resource.runResource`,
-- but constrained by the fine-grained `Resources` effect rather than the super-coarse `IOE`.
runResource :: (Resources :> es) => Eff (Resource : es) a -> Eff es a
runResource = -- implementation is identical to `Effectful.Resource.runResource`
```

I'd love to contribute this work as a PR. 
Let me know what you think! :green_heart:

**Comment by arybczak** [comment]
You can use [Provider](https://hackage.haskell.org/package/effectful-core-2.3.0.0/docs/Effectful-Provider.html) for this.

Your `Resources` effect is `Provider_ Resource ()`, your `runResources` is `runProvider_ (\() -> runResource)` and then you can introduce the `Resource` effect into scope with `provide_ @Resource` :slightly_smiling_face:

**Comment by Qqwy** [comment]
Thank you very much!

Once we're ready to upgrade from 2.2.2.2 to 2.3.0.0 we'll start using `Provider`s :heart_eyes: .
