### ISSUE TITLE
Lifted ResourceT funcitons

### ISSUE THREAD

**Issue by kremovtort** [haskell-effectful/resourcet-effectful#3]
It would be nice to have functions such as `allocate`, but lifted into `Eff` monad.

For example:
```haskell
allocate
  :: Resource :> es
  => Eff es a
  -> (a -> Eff es ())
  -> Eff es (ReleaseKey, a)
``` 

Naive usage `Control.Monad.Trans.Resource.allocate` with `withEffToIO` cause error `version (5) /= storageVersion (0)` for me regardless of chosen unlift strategy.

**Comment by kremovtort** [comment]
I'll send a PR

**Comment by arybczak** [comment]
For the record, I adjusted your PR in 376a121 by adding your variants instead of replacing the original functions with them since they add an overhead of cloning the environment.
